version: '3'
services:
  listing_service_db:
    container_name: search-request-app-db
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: quiz_db_user
      POSTGRES_PASSWORD: pwd_quiz_abc_123
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql